// <auto-generated />
using System;
using System.Text.Json;
using BHS.CRG.Modules.Costs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BHS.CRG.Modules.Costs.Migrations
{
    [DbContext(typeof(CostsDbContext))]
    [Migration("20260929023201_InvoiceScanSize")]
    partial class InvoiceScanSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("costs")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<int?>("DeferralDays")
                        .HasColumnType("integer")
                        .HasColumnName("deferral_days");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("DueDateManual")
                        .HasColumnType("boolean")
                        .HasColumnName("due_date_manual");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<Guid?>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("ScanBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("scan_blob_path");

                    b.Property<string>("ScanFileName")
                        .HasColumnType("text")
                        .HasColumnName("scan_file_name");

                    b.Property<string>("ScanMimeType")
                        .HasColumnType("text")
                        .HasColumnName("scan_mime_type");

                    b.Property<long?>("ScanSize")
                        .HasColumnType("bigint")
                        .HasColumnName("scan_size");

                    b.Property<DateOnly?>("ShippedOn")
                        .HasColumnType("date")
                        .HasColumnName("shipped_on");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.PrimitiveCollection<string[]>("Unconfirmed")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("unconfirmed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("VatTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_total");

                    b.HasKey("Id");

                    b.HasIndex("Payment", "DueDate")
                        .HasDatabaseName("ix_invoices_due");

                    b.HasIndex("SupplierId", "Number", "IssuedOn")
                        .HasDatabaseName("ix_invoices_duplicate");

                    b.ToTable("invoices", "costs");
                });
#pragma warning restore 612, 618
        }
    }
}
