// <auto-generated />
using System;
using System.Text.Json;
using BHS.CRG.Modules.Costs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BHS.CRG.Modules.Costs.Migrations
{
    [DbContext(typeof(CostsDbContext))]
    [Migration("20261008213537_SupplierMatches")]
    partial class SupplierMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("costs")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<int?>("DeferralDays")
                        .HasColumnType("integer")
                        .HasColumnName("deferral_days");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("DueDateManual")
                        .HasColumnType("boolean")
                        .HasColumnName("due_date_manual");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<Guid?>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment");

                    b.Property<string>("PaymentDocument")
                        .HasColumnType("text")
                        .HasColumnName("payment_document");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateOnly?>("RemainderAccountingOn")
                        .HasColumnType("date")
                        .HasColumnName("remainder_accounting_on");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ScanBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("scan_blob_path");

                    b.Property<string>("ScanFileName")
                        .HasColumnType("text")
                        .HasColumnName("scan_file_name");

                    b.Property<string>("ScanMimeType")
                        .HasColumnType("text")
                        .HasColumnName("scan_mime_type");

                    b.Property<long?>("ScanSize")
                        .HasColumnType("bigint")
                        .HasColumnName("scan_size");

                    b.Property<DateOnly?>("ShippedOn")
                        .HasColumnType("date")
                        .HasColumnName("shipped_on");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.PrimitiveCollection<string[]>("Unconfirmed")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("unconfirmed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("VatTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_total");

                    b.HasKey("Id");

                    b.HasIndex("PaidOn")
                        .HasDatabaseName("ix_invoices_paid_on")
                        .HasFilter("paid_on IS NOT NULL");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("ix_invoices_payer")
                        .HasFilter("payer_id IS NOT NULL");

                    b.HasIndex("Payment", "DueDate")
                        .HasDatabaseName("ix_invoices_due");

                    b.HasIndex("SupplierId", "Number", "IssuedOn")
                        .HasDatabaseName("ix_invoices_duplicate");

                    b.ToTable("invoices", "costs", t =>
                        {
                            t.HasCheckConstraint("ck_invoices_paid_on", "(payment = 'Paid') = (paid_on IS NOT NULL) AND (payment = 'Paid' OR remainder_accounting_on IS NULL)");
                        });
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AccountingOn")
                        .HasColumnType("date")
                        .HasColumnName("accounting_on");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid?>("ConstructionId")
                        .HasColumnType("uuid")
                        .HasColumnName("construction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountingOn")
                        .HasDatabaseName("ix_invoice_allocations_accounting")
                        .HasFilter("accounting_on IS NOT NULL");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_invoice_allocations_article")
                        .HasFilter("article_id IS NOT NULL");

                    b.HasIndex("ConstructionId")
                        .HasDatabaseName("ix_invoice_allocations_construction")
                        .HasFilter("construction_id IS NOT NULL");

                    b.HasIndex("LineId");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_invoice_allocations_section")
                        .HasFilter("section_id IS NOT NULL");

                    b.HasIndex("InvoiceId", "LineId", "Ordinal")
                        .HasDatabaseName("ix_invoice_allocations_order");

                    b.ToTable("invoice_allocations", "costs", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_allocations_document_amount", "line_id IS NOT NULL OR (quantity IS NULL AND amount IS NOT NULL)");

                            t.HasCheckConstraint("ck_invoice_allocations_one_target", "(construction_id IS NULL) <> (article_id IS NULL) AND (section_id IS NULL OR construction_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("MatchedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_by");

                    b.Property<Guid?>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierText")
                        .HasColumnType("text")
                        .HasColumnName("supplier_text");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal?>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_unmatched")
                        .HasFilter("nomenclature_id IS NULL");

                    b.HasIndex("NomenclatureId")
                        .HasDatabaseName("ix_invoice_lines_nomenclature")
                        .HasFilter("nomenclature_id IS NOT NULL");

                    b.HasIndex("InvoiceId", "Ordinal")
                        .HasDatabaseName("ix_invoice_lines_order");

                    b.ToTable("invoice_lines", "costs");
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceRecognition", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Engine")
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<JsonDocument>("Lines")
                        .HasColumnType("jsonb")
                        .HasColumnName("lines");

                    b.PrimitiveCollection<string[]>("Notes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("notes");

                    b.Property<JsonDocument>("Offers")
                        .HasColumnType("jsonb")
                        .HasColumnName("offers");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("ScanBlobPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scan_blob_path");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<JsonDocument>("Values")
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.HasKey("InvoiceId");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_invoice_recognitions_outcome");

                    b.ToTable("invoice_recognitions", "costs");
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.SupplierMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("key_hash")
                        .IsFixedLength();

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_name");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId")
                        .HasDatabaseName("ix_supplier_matches_nomenclature");

                    b.HasIndex("SupplierId", "Kind", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_matches_key");

                    b.ToTable("supplier_matches", "costs");
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.Waybill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConstructionId")
                        .HasColumnType("uuid")
                        .HasColumnName("construction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("received_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Warehouse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("warehouse");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId", "IssuedOn")
                        .HasDatabaseName("ix_waybills_issued")
                        .HasFilter("state = 'Posted'");

                    b.ToTable("waybills", "costs", t =>
                        {
                            t.HasCheckConstraint("ck_waybills_posted", "state <> 'Posted' OR (issued_on IS NOT NULL AND construction_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.WaybillLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("SourceText")
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WaybillId")
                        .HasColumnType("uuid")
                        .HasColumnName("waybill_id");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId")
                        .HasDatabaseName("ix_waybill_lines_nomenclature")
                        .HasFilter("nomenclature_id IS NOT NULL");

                    b.HasIndex("WaybillId")
                        .HasDatabaseName("ix_waybill_lines_unmatched")
                        .HasFilter("nomenclature_id IS NULL");

                    b.HasIndex("WaybillId", "Ordinal")
                        .HasDatabaseName("ix_waybill_lines_order");

                    b.ToTable("waybill_lines", "costs");
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceAllocation", b =>
                {
                    b.HasOne("BHS.CRG.Modules.Costs.Data.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BHS.CRG.Modules.Costs.Data.InvoiceLine", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceLine", b =>
                {
                    b.HasOne("BHS.CRG.Modules.Costs.Data.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.InvoiceRecognition", b =>
                {
                    b.HasOne("BHS.CRG.Modules.Costs.Data.Invoice", null)
                        .WithOne()
                        .HasForeignKey("BHS.CRG.Modules.Costs.Data.InvoiceRecognition", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BHS.CRG.Modules.Costs.Data.WaybillLine", b =>
                {
                    b.HasOne("BHS.CRG.Modules.Costs.Data.Waybill", null)
                        .WithMany()
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
