// Design-system barrel for /design-sync (gitignored, generated by the sync).
// Re-exports ONLY the reusable shared/ui primitives so the esbuild bundle is
// scoped to the design system and doesn't drag the whole app (api/router/monaco).
// Sub-exports (SelectItem, NavItem, DetailHeader, CascadeList, DateInput) and the
// ThemeProvider ride along for composition inside preview cards.
export * from './src/shared/ui/Button';
export * from './src/shared/ui/Switch';
export * from './src/shared/ui/TextField';
export * from './src/shared/ui/DateInput';
export * from './src/shared/ui/DateField';
export * from './src/shared/ui/Select';
export * from './src/shared/ui/Modal';
export * from './src/shared/ui/ConfirmDialog';
export * from './src/shared/ui/RowActionsMenu';
export * from './src/shared/ui/TypePicker';
export * from './src/shared/ui/ListDetailShell';
export * from './src/shared/ui/EmptyState';
export * from './src/shared/ui/ShortcutsHelp';
export * from './src/shared/ui/ThemeProvider';
